from enum import Enum;

class API_ERROR_ENUMS(Enum):
  """
  Enums for API error messages.
  """
  DATA_NOT_JSON = "DATA NOT JSON";
  
  INVALID_USERNAME = "INVALID USERNAME";
  INVALID_EMAIL = "INVALID EMAIL"
  INVALID_PASSWORD = "INVALID PASSWORD";
  
  USERNAME_TAKEN = "USERNAME IS TAKEN";
  EMAIL_TAKEN = "EMAIL IS ALREADY IN USE";