from enum import Enum;

class FLASK_ENVIRONMENT_ENUMS(Enum):
  DEVELOPMENT = "development";
  TESTING = "testing";
  PRODUCTION = "production";
  
class API_ERRORS(Enum):
  DATA_NOT_JSON = "DATA NOT JSON";
  
  INVALID_USERNAME = "INVALID USERNAME";
  INVALID_EMAIL = "INVALID EMAIL"
  INVALID_PASSWORD = "INVALID PASSWORD";
  
  USERNAME_TAKEN = "USERNAME IS TAKEN";
  EMAIL_TAKEN = "EMAIL IS ALREADY IN USE";
  
class HTTP_RETURN_CODES(Enum):
  OK = 200;
  CREATED = 201;
  
  BAD_REQUEST = 400;
  INTERNAL_CONFLICT = 409;
  
  UNAUTHORIZED = 401;
  INTERNAL_SERVER_ERROR = 500;